# Site settings
name: Funktum
description: Funktum on liikunta-alan yritys joka tarjoaa henkilökohtaista valmennusta ja ryhmäliikuntaa.
url: http://www.funktum.fi
ga: UA-66809541-1
baseurl: ""
share_image: /assets/img/opengraph_share.png
github: [metadata]

# Contact details
sampsa:
  full_name: Sampsa Visuri
  email: sampsa@funktum.fi
  phone: +358403513174
  phone_formatted: +358 40 351 3174

linnea:
  full_name: Linnea Lindgård
  email: linnea@funktum.fi
  phone: +358440612955
  phone_formatted: +358 44 061 2955

tommy:
  full_name: Tommy Borg
  email: tommy@funktum.fi
  phone: +358442546460
  phone_formatted: +358 44 254 6460

# Build settings
markdown: kramdown
permalink: pretty

# Blog settings
paginate: 20
paginate_path: "/blog/page/:num/"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      category: blog
      is_post: true

# Prose.io settings
prose:
  siteurl: http://www.funktum.fi/
  relativeLinks: http://www.funktum.fi/links.jsonp
  media: media
  ignore:
    - /_sass
    - /_site
    - /_layouts
    - /_includes
    - /blog
    - /assets
    - _config*
    - .git*
    - Gem*
    - CNAME
    - links.jsonp
    - favicon.ico
  metadata:
    "":
      - name: layout
        field:
          element: hidden
          value: page
      - name: published
        field:
          element: checkbox
          label: Publish
          help: Uncheck if you don't want to publish the page right now
          value: true
      - name: title
        field:
          element: text
          label: Title
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: published
        field:
          element: checkbox
          label: Publish
          help: Uncheck if you don't want to publish the post right now
          value: true
      - name: title
        field:
          element: text
          label: Title

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO
  - vendor

# Plugins to use
plugins:
  - jekyll-paginate
  - jekyll-sitemap