# Site settings
name: Funktum
email: sampsa@funktum.fi
description: Funktum on erikoistunut toiminnalliseen henkilökohtaiseen valmennukseen ja ryhmäliikuntaan. Tarjoamme myös luentoja esimerkiksi yrityksille. Toimialueemme on pääkaupunkiseutu.
url: http://www.funktum.fi
ga: UA-66809541-1
baseurl: ""
permalink: pretty

# Blog settings
paginate: 5
paginate_path: "/blog/page/:num/"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:title/
      is_post: true

# Prose.io settings
prose:
  siteurl: 'http://www.funktum.fi/'
  relativeLinks: 'http://www.funktum.fi/links.jsonp'
  media: 'media'
  ignore:
    - /_sass
    - /_site
    - /_layouts
    - /_includes
    - /blog
    - /js
    - /fonts
    - /css
    - _config*
    - .git*
    - Gem*
    - CNAME
    - links.jsonp
    - favicon.ico
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Post title"

# Build settings
markdown: kramdown

# Set the Sass partials directory, as we're using @imports
sass:
    style: :compressed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - TODO

# Gems to use
gems:
  - octopress-autoprefixer
  - jekyll-auto-image
