# Site settings
name: Funktum
email: sampsa@funktum.fi
description: Funktum on erikoistunut toiminnalliseen henkilökohtaiseen valmennukseen ja toiminnalliseen ryhmäliikuntaan. Tarjoamme myös luentoja terveyden perusasioista esimerkiksi yrityksille.
url: http://funktum.fi
ga: UA-66809541-1
baseurl: ""

# Build settings
markdown: kramdown