# Site settings
name: Funktum
email: sampsa@funktum.fi
description: Funktum on erikoistunut toiminnalliseen henkilökohtaiseen valmennukseen ja toiminnalliseen ryhmäliikuntaan. Tarjoamme myös luentoja terveyden perusasioista esimerkiksi yrityksille.
url: http://funktum.fi
ga: UA-66809541-1
baseurl: ""
buttonurl: "/palvelut/"

# Build settings
markdown: kramdown

# Set the Sass partials directory, as we're using @imports
sass:
    style: :compressed


# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
